### PR TITLE
Create go.yml

### PR DESCRIPTION
**Pull request by alexDtorres**

### CODE REVIEW

**Comment by justinclift** [comment]
Interesting idea.  What was it for? :smile:

**Comment by alexDtorres** [comment]
Was an accidental PR; my apologies 😅 

I believe the changes were:
- add workflow to verify go module is installable with `go install`
- change `README.md` to include status badge of added workflow
- rename the go module for GOPATH compatibility (I think I'm doing something wrong here) 

Edit: 
- change default branch of repo from `master` to `main`

**Comment by alexDtorres** [comment]
I'm currently using `sqlite3` and `dio` in combination as a (painful) means of source code management.

For instance, each source file could be represented as a row in a `Units` table. From there, I'd like to use `dio` for merging and diffing table cells. Unfortunately I haven't gotten very far yet on that last part lol

Thanks for the reply! 🐐

**Comment by justinclift** [comment]
No worries at all, it's an interesting concept. :smile:

**Pull request closed without merging**
